<?php

namespace AppBundle\Repository;

/**
 * LendMTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LendMTRepository extends \Doctrine\ORM\EntityRepository
{
}
