<?php

namespace AppBundle\Repository;

/**
 * MoveProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveProdRepository extends \Doctrine\ORM\EntityRepository
{
}
