<?php

namespace AppBundle\Repository;

/**
 * ProdTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
